# Generated by Django 3.2.16 on 2022-11-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0002_rename_req_id_plot_reqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='reqid',
            field=models.CharField(max_length=32, unique=True, verbose_name='Регистрационный номер земельного участка'),
        ),
    ]
