# Generated by Django 3.2.16 on 2022-11-26 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0003_alter_plot_reqid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crop',
            options={'verbose_name': 'Культура', 'verbose_name_plural': 'Культуры'},
        ),
        migrations.AlterModelOptions(
            name='plot',
            options={'verbose_name': 'Участок', 'verbose_name_plural': 'Участки'},
        ),
        migrations.CreateModel(
            name='BookChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_channels', to='plots.plot')),
            ],
            options={
                'verbose_name': 'Бронь канала',
                'verbose_name_plural': 'Бронь каналов',
            },
        ),
    ]
