# Generated by Django 3.2.16 on 2022-11-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0004_auto_20221126_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookchannel',
            name='date',
            field=models.DateField(unique_for_date=True),
        ),
    ]
