# Generated by Django 3.2.16 on 2022-11-26 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0005_alter_bookchannel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookchannel',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookchannel',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_channels', to='plots.plot', unique_for_date='date'),
        ),
    ]
