# Generated by Django 3.2.16 on 2022-11-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0006_auto_20221126_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='water_consumption',
            field=models.IntegerField(default=0, verbose_name='Расход воды за 1га в кубометрах'),
            preserve_default=False,
        ),
    ]
